const SKILLS = [
  { category: "Technical", skills: "React js" },
  { category: "Technical", skills: "Javascript" },
  { category: "Technical", skills: "CSS" },
  { category: "Technical", skills: "HTML5" },
  { category: "Technical", skills: "PowerShell" },
  { category: "Technical", skills: "SQL Server" },
  { category: "Technical", skills: "PostgreSQL" },
  { category: "Technical", skills: "C" },
  { category: "Technical", skills: "C++" },
  { category: "Technical", skills: "C#" },
  { category: "Technical", skills: "PHP" },
  { category: "Technical", skills: "Python" },
  { category: "Technical", skills: "LabVIEW" },
  { category: "Technical", skills: "Matlab" },
  { category: "Technical", skills: "Git" },
  { category: "Technical", skills: "JIRA" },
  { category: "Technical", skills: "Confluence" },
  { category: "Technical", skills: "Postman" },
  { category: "Technical", skills: "SOAP UI" },
  { category: "Technical", skills: "Zilog ZDS II" },
  { category: "Technical", skills: "RIMU PCB" },
  { category: "Technical", skills: "PSPICE" },
  { category: "Language", skills: "English" },
  { category: "Language", skills: "Malay" },
  { category: "Language", skills: "Chinese" },
  { category: "Others", skills: "Toastmaster" },
  { category: "Others", skills: "Guitar" },
  { category: "Others", skills: "Organ" },
];

export default SKILLS;
